version: '3.1'
services:
  web:
    build: .
    image: gowebapp
    restart: always
    ports:
      - ${APPPORT:-8080}:8080 # Make host port variable, default is 8080
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: bird_encyclopedia
    volumes:
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
