# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example

  web:
    build: .
    image: gowebapp
    restart: always
    ports:
      - 8080:8080